kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-node
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-node
  template:
    metadata:
      name: hello-node
      labels:
        name: hello-node
    spec:
      serviceAccountName: sa
      containers:
      - name: hello-node
        image: ykum01/helloworld:49
        ports:
        - containerPort: 3000
        imagePullPolicy: Always