apiVersion: v1
kind: Service
metadata:
     name: node-svc
     namespace: default
spec:
   selector:
       name: hello-node
   ports:
     - protocol: "TCP"
       port: 80
       targetPort: 3000 
   type: NodePort