name: Build and Push Docker Image Into DockerHub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_ID}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build And Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: . #  Here the . represents the root directory of the repository where the workflow is running. We can change this value if our Dockerfile is located in a different directory.
        push: true
        tags: ykum01/helloworld:${{github.run_number}}

  modifydeploymentgit:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: changing the deployment of git repo
      with:
        repository: 'Yashk0198/node-hello'
    - name: modify the image
      run: |
        git config user.email yavsh123@gmail.com
        git config user.name Yash
        pwd
        cat node-hello/templates/deployment.yaml
        pwd
        sed -i "s+ykum01/helloworld.*+ykum01/helloworld:$RUN_NUMBER+g" node-hello/templates/deployment.yaml
        # cat deployment.yml
        git add .
        git commit -m 'Done  by Github Actions job change manifest: ${{ github.run_number }}'
        git push origin main
      env:
        RUN_NUMBER: ${{ github.run_number }}
